[package]
name = "cli-batteries"
description = "Batteries included opinionated command line interfaces"
authors = ["Remco Bloemen <remco@wicked.ventures>"]
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/recmo/cli-batteries"
repository = "https://github.com/recmo/cli-batteries"
keywords = ["cli"]
categories = ["cli"]
readme = "Readme.md"
license = "MIT"

[dependencies]
chrono = "0.4"
color-eyre = { version = "0.6", features = [ "issue-url" ] }
console-subscriber = { version = "0.1", optional = true }
criterion = { version = "0.3", optional = true, features = [ "async_tokio" ] }
eyre = "0.6"
futures = "0.3"
hex = "0.4.3"
hex-literal = "0.3"
itertools = "0.10"
mimalloc = { version = "0.1", default-features = false, optional = true }
once_cell = "1.8"
proptest = { version = "1.0", optional = true }
structopt = "0.3"
thiserror = "1.0"
tokio = { version = "1.17", features = [ "signal", "fs", "macros", "rt", "sync", "time", "rt-multi-thread", "tracing" ] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = [ "env-filter", "json" ] }
users = "0.11"

time = { version = "0.3.5", features = [ "formatting", "parsing" ] }

[dev-dependencies]
proptest = { version = "1.0" }
tracing-test = "0.2"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
overflow-checks = true
strip = true

# Compilation profile for any non-workspace member.
# Dependencies are optimized, even in a dev build. This improves dev performance
# while having neglible impact on incremental build times.
[profile.dev.package."*"]
opt-level = 3
